### ISSUE TITLE
Incorrect volume mount in nodejs-postgresql-persistent template

### ISSUE THREAD

**Issue by nimasamii** [openshift/cluster-samples-operator#382]
The template creates a PVC and mounts it to `/var/lib/postgresql/data` in the DB container. However the correct path is `/var/lib/pgsql/data`. This leads to data loss, when the DB container is restarted for any reason (e.g. update of the base image).

**Comment by gabemontero** [comment]
Hello @nimasamii 

While this repository simply hosts this template, it is not the "source" for the template, nor are the maintainers of this repo the maintainer for the actual contents of this template.

Templates like those are owned by the SCL org at https://github.com/sclorg

As they make various updates upstream, those updates are first pulled into https://github.com/openshift/library, and then we periodically pull that https://github.com/openshift/library content into this repo (typically once per OCP release, as we get close to shutting a OCP release down for GA).

As it turns out, looks like that team caught the situation recently, and https://github.com/openshift/cluster-samples-operator/pull/381 from @dperaza4dustbit will be bringing in that fix.

While that will update it for the upcoming 4.9, for us to backport that specific fix to 4.7 or 4.8, we would need a bugzilla to do so per the OCP process.  Let us know if you are unable to file a support case or open a bugzilla directly, and we can see about opening a bz for you.

Note, for 4.6, with where it is in this life cycle, a fix of this severity won't qualify for a backport.  The work around would be for someone with sufficient permissions on the cluster to edit the template manually.  Samples operator will not immediately overwrite this fix if you simply patch the template.
