### ISSUE TITLE
Operator does not seems to be using the cluster-wide proxy setting

### ISSUE THREAD

**Issue by vittico** [openshift/cluster-samples-operator#427]
The proxy/cluster configuration is as follows:

~~~
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: "2022-04-27T15:25:53Z"
  generation: 10
  name: cluster
  resourceVersion: "13304816"
  uid: 88fc90e8-eae6-4641-8175-3c9b1f4e303e
spec:
  httpProxy: http://xxx.xxx.xxx.xxx:80
  httpsProxy: http://xxx.xxx.xxx.xxx:80
  noProxy: [some domains/host here]
~~~

This proxy variables are inherited by openshift pods, such as cluster-image-registry-operator, but they aren't by cluster-samples-operator, so that we are not able to access registry.redhat.io for images updates.

~~~
[oddd@dfdsd]$ oc rsh cluster-samples-operator-7dffb458cd-phsdx
Defaulted container "cluster-samples-operator" out of: cluster-samples-operator, cluster-samples-operator-watch
sh-4.4$ curl -v -k https://registry.redhat.io
* Rebuilt URL to: https://registry.redhat.io/
*   Trying 184.24.69.179...
* TCP_NODELAY set
~~~
Nevertheless, if we export the proxy environment variables inside the pod:

~~~
sh-4.4$ export HTTP_PROXY=http://proxy.host:80
sh-4.4$ export HTTPS_PROXY=http://proxy.host:80
sh-4.4$ curl -v -k https://registry.redhat.io
* Rebuilt URL to: https://registry.redhat.io/
* Uses proxy env variable HTTPS_PROXY == 'http://proxy.host:80'
*   Trying 165.225.92.13...
* TCP_NODELAY set
~~~

**Comment by gabemontero** [comment]
hi @vittico 

samples operator do not do the actual import of the image into the image streams; it just creates/updates the sample image streams

you should open this in https://github.com/openshift/image-registry/

**Comment by dperaza4dustbit** [comment]
Hello @vittico can you confirm we can close this one? thanks

**Comment by germanparente** [comment]
hi @gabemontero before closing this issue, could you explain why the samples operator is not inheriting the proxy variables and it's not using the cluster wide proxy ? Is this harmless ? 

Thanks in advance.

**Comment by gabemontero** [comment]
@vittico @germanparente - a common point of confusion, but the samples operator itself does not reach out to the image registries to pull images; it only creates and manages openshift API objects, specifically imagestreams and templates.

when samples operator does create imagestreams objects, it is then the imagestream subsystem (a combination of the imagestream controller in the openshift controller manager operator, openshift's internal image registry, and the imagestream endpoints in the openshift api server) that has to consume the the cluster wide proxy settings when it communicates with image registries referenced by the imagestreams it processes.

that is why I directed you all to open items against one of the imagestream related repos instead of this one; 

@dperaza4dustbit this most certainly can be close; reach out to me in our slack channel if my explanation ^^ does not make sense, or if @germanparente / @vittico have further questions you cannot answer.

**Comment by germanparente** [comment]
thanks a lot for explanation.
